services:
  - type: web
    name: floatchat-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
    autoDeploy: true
    buildFilter:
      paths:
        - backend/**
    rootDir: backend
